vim.cmd.colorscheme("onedark")

require("config.special")
require("config.icons")
require("config.options")
require("config.mappings")
require("config.autocmds")
require("config.lsp")
require("config.statusline")
require("config.commands")
