return function(Group, c, g, s)
    Group.new("Normal", c.white, c.black)
    Group.new("Comment", c.white_dark)

    Group.new("Pmenu", nil, c.black_light)
    Group.new("PmenuSbar", nil, c.black_light)
    Group.new("PmenuSel", c.black, c.blue)
    Group.new("PmenuThumb", nil, c.grey)

    Group.new("MatchWord", c.white, c.grey)
    Group.link("MatchParen", g.MatchWord)

    Group.new("CursorLineNr", c.white)
    Group.new("LineNr", c.grey)

    Group.new("NormalFloat", nil, c.black_dark)
    Group.new("FloatTitle", c.white, c.grey)
    Group.new("FloatBorder", c.blue)
    Group.new("WinSeparator", c.grey)

    Group.new("Error", c.red)
    Group.link("ErrorMsg", g.Error)
    Group.link("NvimInternalError", g.Error)
    Group.link("Exception", g.Error)

    Group.new("WarningMsg", c.yellow)
    Group.new("ModeMsg", c.base0B)
    Group.new("MoreMsg", c.base0B)

    Group.new("Directory", c.blue)
    Group.new("Folded", c.grey_light, c.black_light)
    Group.new("IncSearch", c.base01, c.base09)
    Group.new("Macro", c.base08)
    Group.new("Question", c.base0D)
    Group.new("Search", c.base01, c.base0A, s.bold)
    Group.new("Substitute", c.base01, c.base0A)
    Group.new("SpecialKey", c.base03)
    Group.link("TooLong", g.Normal)
    Group.new("Visual", nil, c.base02)
    Group.new("VisualNOS", c.base08)
    Group.new("WildMenu", c.base08, c.base0A)
    Group.new("Title", c.base0D)
    Group.new("NonText", c.base03)
    Group.new("Cursor", c.base00, c.base05)
    Group.new("SignColumn", c.base03)
    Group.new("ColorColumn", nil, c.black_light)
    Group.new("CursorColumn", nil, c.base01)
    Group.new("CursorLine", nil, c.black_light)
    Group.new("QuickFixLine", nil, c.base01)
    Group.new("healthSuccess", c.black, c.green)
end
