return function(new, c, g, s)
    -- nvim
    new("Info",              c.green,       c.black,      nil         )
    new("DiagnosticInfo",    g.Info,        g.Info,       g.Info      )
    new("Warn",              c.yellow,      c.black,      s.bold      )
    new("DiagnosticWarn",    g.Warn,        g.Warn,       g.Warn      )
    new("Error",             c.white,       c.red,        s.bold      )
    new("ErrorMsg",          g.Error,       g.Error,      g.Error     )
    new("DiagnosticError",   g.Error,       g.Error,      g.Error     )
    new("NvimInternalError", g.Error,       g.Error,      g.Error     )
    -- new("CursorLine",        nil,           c.gray,       nil         )
    -- new("CursorColumn",      g.CursorLine,  g.CursorLine, g.CursorLine)
    -- new("DiffAdd",           c.green,       nil,          nil         )
    -- new("DiffChange",        c.white,       nil,          nil         )
    -- new("DiffDelete",        c.red,         nil,          nil         )
    -- new("Directory",         c.olive,       nil,          nil         )
    -- new("LineNr",            c.yellow,      nil,          nil         )
    -- new("LineNrAbove",       c.silver,      nil,          nil         )
    -- new("LineNrBelow",       g.LineNrAbove, nil,          nil         )
    -- new("PMenuSel",          c.black,       c.lime,       nil         )
    -- new("StatusLine",        c.blue,           c.red,        nil         )
    -- new("StatusLineNC",      nil,           c.black,      nil         )
    -- new("VertSplit",         c.white,       nil,          nil         )
    -- new("Search",            nil,           c.green,      nil         )
    -- new("WildMenu",          g.Search,      g.Search,     g.Search    )

    -- treesitter
    -- new("TSComment",        c.silver,  nil,      nil)
    -- new("TSConstBuiltin",   c.aqua,    nil,      nil)
    -- new("TSConstMacro",     c.blue,    nil,      nil)
    -- new("TSConstant",       c.aqua,    nil,      nil)
    -- new("TSConstructor",    c.teal,    nil,      nil)
    -- new("TSDanger",         c.black,   c.red,    nil)
    -- new("TSField",          c.white,   nil,      nil)
    -- new("TSFuncMacro",      c.yellow,  nil,      nil)
    -- new("TSFunction",       c.red,     nil,      nil)
    -- new("TSInclude",        c.maroon,  nil,      nil)
    -- new("TSInclude",        c.teal,    nil,      nil)
    -- new("TSKeyword",        c.teal,    nil,      nil)
    -- new("TSLabel",          c.fuchsia, nil,      nil)
    -- new("TSNamespace",      c.white,   nil,      nil)
    -- new("TSNote",           c.black,   c.white,  nil)
    -- new("TSOperator",       c.red,     nil,      nil)
    -- new("TSProperty",       c.white,   nil,      nil)
    -- new("TSPunctBracket",   c.white,   nil,      nil)
    -- new("TSPunctDelimiter", c.red,     nil,      nil)
    -- new("TSPunctSpecial",   c.red,     nil,      nil)
    -- new("TSString",         c.lime,    nil,      nil)
    -- new("TSType",           c.fuchsia, nil,      nil)
    -- new("TSTypeBuiltin",    c.fuchsia, nil,      nil)
    -- new("TSVariable",       c.white,   nil,      nil)
    -- new("TSWarning",        c.black,   c.yellow, nil)
end
