return function(Group, c, g, s)
    Group.new("Normal", c.white, c.black)

    Group.new("WinSeparator", c.grey)

    Group.new("Pmenu", nil, c.grey_dark)
    Group.new("PmenuSbar", nil, c.grey_light)
    Group.new("PmenuSel", c.black, c.blue)
    Group.new("PmenuThumb", nil, c.grey_light)

    Group.new("MatchWord", c.white, c.grey)
    Group.link("MatchParen", g.MatchWord)

    Group.new("LineNr", c.grey)
    Group.new("CursorLineNr", c.white)
    Group.link("TooLong", g.Normal)

    Group.link("NormalFloat", g.Normal)
    Group.new("FloatTitle", c.white, c.grey)
    Group.new("NoBorder", c.black_dark, c.black_dark)
    Group.new("BlueBorder", c.blue, g.Normal)
    Group.new("GreyBorder", c.white_dark, g.Normal)
    Group.link("FloatBorder", g.BlueBorder)

    Group.new("Error", c.red)
    Group.link("ErrorMsg", g.Error)
    Group.link("NvimInternalError", g.Error)
    Group.link("Exception", g.Error)

    Group.new("WarningMsg", c.yellow)
    Group.new("ModeMsg", c.base0B)
    Group.new("MoreMsg", c.base0B)

    Group.new("Directory", c.blue)
    Group.new("Folded", c.grey_light, c.black_light)
    Group.new("Search", c.yellow, c.yellow_bg, s.bold)
    Group.link("IncSearch", g.Search)
    Group.new("Macro", c.base08)
    Group.new("Question", c.base0D)
    Group.new("Substitute", c.base01, c.base0A)
    Group.new("SpecialKey", c.base03)
    Group.new("Visual", nil, c.base02)
    Group.new("VisualNOS", c.base08)
    Group.new("WildMenu", c.base08, c.base0A)
    Group.new("Title", c.base0D)
    Group.new("NonText", c.base03)
    Group.new("Cursor", c.base00, c.base05)
    Group.new("SignColumn", c.base03)
    Group.new("ColorColumn", nil, c.black_light)
    Group.new("CursorColumn", nil, c.base01)
    Group.new("CursorLine", nil, c.black_light)
    Group.new("QuickFixLine", nil, c.base01)
end
