return function(Group, c, g, s)
    -- default
    Group.new("Comment", c.base04)
    Group.new("Boolean", c.base09)
    Group.new("Character", c.base08)
    Group.new("Conditional", c.base0E)
    Group.new("Constant", c.base09)
    Group.new("Define", c.base0E)
    Group.new("Delimiter", c.base0F)
    Group.new("Float", c.base09)
    Group.new("Variable", c.base05)
    Group.new("Function", c.base0D)
    Group.new("Identifier", c.base08)
    Group.new("Include", c.base0D)
    Group.new("Keyword", c.base0E)
    Group.new("Label", c.base0A)
    Group.new("Number", c.base09)
    Group.new("Operator", c.base05)
    Group.new("PreProc", c.base0A)
    Group.new("Repeat", c.base0A)
    Group.new("Special", c.base0C)
    Group.new("SpecialChar", c.base0F)
    Group.new("Statement", c.base08)
    Group.new("StorageClass", c.base0A)
    Group.new("String", c.base0B)
    Group.new("Structure", c.base0E)
    Group.new("Tag", c.base0A)
    Group.new("Todo", c.base0A, c.base01)
    Group.new("Type", c.base0A)
    Group.new("Typedef", c.base0A)

    -- treesitter
    Group.new("@module", c.base08)
    Group.new("@module.builtin", c.base08)

    Group.new("@constant", c.base09)
    Group.new("@constant.builtin", c.base09)
    Group.new("@constant.macro", c.base08)
    Group.new("@constant.macro", c.base08)

    Group.new("@string", c.base0B)
    Group.new("@string.regex", c.base0C)
    Group.new("@string.escape", c.base0C)
    Group.new("@character", c.base08)
    Group.new("@character.special", c.base08)
    Group.new("@number", c.base09)
    Group.new("@number.float", c.base09)
    Group.new("@boolean", c.base09)

    Group.new("@annotation", c.base0F)
    Group.new("@attribute", c.base0A)
    Group.new("@error", c.base08)

    Group.new("@keyword", c.base0E)
    Group.new("@keyword.exception", c.base08)
    Group.new("@keyword.function", c.base0E)
    Group.new("@keyword.return", c.base0E)
    Group.new("@keyword.operator", c.base0E)
    Group.new("@keyword.conditional", c.base0E)
    Group.new("@keyword.conditional.ternary", c.base0E)
    Group.new("@keyword.repeat", c.base0A)
    Group.new("@keyword.storage", c.base0A)
    Group.new("@keyword.directive.define", c.base0E)
    Group.new("@keyword.directive", c.base0A)

    Group.new("@function", c.base0D)
    Group.new("@function.builtin", c.base0D)
    Group.new("@function.macro", c.base08)
    Group.new("@function.call", c.base0D)
    Group.new("@function.method", c.base0D)
    Group.new("@function.method.call", c.base0D)
    Group.new("@constructor", c.base0C)

    Group.new("@punctuation.bracket", c.base0F)
    Group.new("@punctuation.delimiter", c.base0F)

    Group.new("@tag", c.base0A)
    Group.new("@tag.attribute", c.base08)
    Group.new("@tag.delimiter", c.base0F)

    Group.new("@text", c.base05)
    Group.new("@text.emphasis", c.base09)
    Group.new("@text.strike", c.base0F, nil, s.strikethrough)

    Group.new("@type.builtin", c.base0A)

    Group.new("@operator", c.base05)
    Group.new("@symbol", c.base0B)
    Group.new("@reference", c.base05)
    Group.new("@definition", c.base04, nil, s.underline)
    Group.new("@property", c.base08)
    Group.new("@scope", nil, nil, s.bold)

    Group.new("@markup.heading", c.base0D)
    Group.new("@markup.raw", c.base09)
    Group.new("@markup.link", c.base08)
    Group.new("@markup.link.url", c.base09, nil, s.underline)
    Group.new("@markup.link.label", c.base0C)
    Group.new("@markup.list", c.base08)
    Group.new("@markup.strong", nil, nil, s.bold)
    Group.new("@markup.underline", nil, nil, s.underline)
    Group.new("@markup.italic", nil, nil, s.italic)
    Group.new("@markup.strikethrough", nil, nil, s.strikethrough)
    Group.new("@markup.quote", c.black_light)

    Group.link("@comment", g.Comment)
    Group.new("@comment.todo", c.grey, c.white)
    Group.new("@comment.warning", c.black_light, c.base09)
    Group.new("@comment.note", c.black, c.blue)
    Group.new("@comment.danger", c.black_light, c.red)

    Group.new("@diff.plus", c.green)
    Group.new("@diff.minus", c.red)
    Group.new("@diff.delta", c.grey)
end
